name: Generate and Deploy Stats Visualization

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 2 * * *' # daily at 2am UTC

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .

      - name: Generate visualization
        run: |
          python visualize_stats.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PUBLIC_REPO_PAT }}
          publish_dir: gh_pages
          publish_branch: gh-pages
          keep_files: false
          force_orphan: true
